const LOCALES = [
	{ currency: 'AED', locale: 'ar-AE' },
	{ currency: 'ALL', locale: 'sq-AL' },
	{ currency: 'ARS', locale: 'es-AR' },
	{ currency: 'AUD', locale: 'en-AU' },
	{ currency: 'BAM', locale: 'sr-BA' },
	{ currency: 'BGN', locale: 'bg-BG' },
	{ currency: 'BHD', locale: 'ar-BH' },
	{ currency: 'BOB', locale: 'es-BO' },
	{ currency: 'BRL', locale: 'pt-BR' },
	{ currency: 'BYN', locale: 'be-BY' },
	{ currency: 'CAD', locale: 'en-CA' },
	{ currency: 'CHF', locale: 'de-CH' },
	{ currency: 'CLP', locale: 'es-CL' },
	{ currency: 'CNY', locale: 'zh-CN' },
	{ currency: 'COP', locale: 'es-CO' },
	{ currency: 'CRC', locale: 'es-CR' },
	{ currency: 'CSD', locale: 'sr-CS' },
	{ currency: 'CUP', locale: 'es-CU' },
	{ currency: 'CZK', locale: 'cs-CZ' },
	{ currency: 'DKK', locale: 'da-DK' },
	{ currency: 'DOP', locale: 'es-DO' },
	{ currency: 'DZD', locale: 'ar-DZ' },
	{ currency: 'EGP', locale: 'ar-EG' },
	{ currency: 'EUR', locale: 'en-IE' },
	{ currency: 'GBP', locale: 'en-GB' },
	{ currency: 'GTQ', locale: 'es-GT' },
	{ currency: 'HKD', locale: 'zh-HK' },
	{ currency: 'HNL', locale: 'es-HN' },
	{ currency: 'HRK', locale: 'hr-HR' },
	{ currency: 'HUF', locale: 'hu-HU' },
	{ currency: 'IDR', locale: 'in-ID' },
	{ currency: 'ILS', locale: 'iw-IL' },
	{ currency: 'INR', locale: 'en-IN' },
	{ currency: 'IQD', locale: 'ar-IQ' },
	{ currency: 'ISK', locale: 'is-IS' },
	{ currency: 'JOD', locale: 'ar-JO' },
	{ currency: 'JPY', locale: 'ja-JP' },
	{ currency: 'KRW', locale: 'ko-KR' },
	{ currency: 'KWD', locale: 'ar-KW' },
	{ currency: 'LBP', locale: 'ar-LB' },
	{ currency: 'LYD', locale: 'ar-LY' },
	{ currency: 'MAD', locale: 'ar-MA' },
	{ currency: 'MKD', locale: 'mk-MK' },
	{ currency: 'MXN', locale: 'es-MX' },
	{ currency: 'MYR', locale: 'ms-MY' },
	{ currency: 'NIO', locale: 'es-NI' },
	{ currency: 'NOK', locale: 'no-NO' },
	{ currency: 'NZD', locale: 'en-NZ' },
	{ currency: 'OMR', locale: 'ar-OM' },
	{ currency: 'PAB', locale: 'es-PA' },
	{ currency: 'PEN', locale: 'es-PE' },
	{ currency: 'PHP', locale: 'en-PH' },
	{ currency: 'PLN', locale: 'pl-PL' },
	{ currency: 'PYG', locale: 'es-PY' },
	{ currency: 'QAR', locale: 'ar-QA' },
	{ currency: 'RON', locale: 'ro-RO' },
	{ currency: 'RSD', locale: 'sr-RS' },
	{ currency: 'RUB', locale: 'ru-RU' },
	{ currency: 'SAR', locale: 'ar-SA' },
	{ currency: 'SDG', locale: 'ar-SD' },
	{ currency: 'SEK', locale: 'sv-SE' },
	{ currency: 'SGD', locale: 'en-SG' },
	{ currency: 'SVC', locale: 'es-SV' },
	{ currency: 'SYP', locale: 'ar-SY' },
	{ currency: 'THB', locale: 'th-TH' },
	{ currency: 'TND', locale: 'ar-TN' },
	{ currency: 'TRY', locale: 'tr-TR' },
	{ currency: 'TWD', locale: 'zh-TW' },
	{ currency: 'UAH', locale: 'uk-UA' },
	{ currency: 'USD', locale: 'en-US' },
	{ currency: 'UYU', locale: 'es-UY' },
	{ currency: 'VEF', locale: 'es-VE' },
	{ currency: 'VND', locale: 'vi-VN' },
	{ currency: 'YER', locale: 'ar-YE' },
	{ currency: 'ZAR', locale: 'en-ZA' }
];

const formatCurrency = (number, currency, symbol) => {
	let locale = LOCALES.find(x => x.currency === currency).locale;
	return (
		symbol +
		' ' +
		number.toLocaleString(locale, {
			currency: currency
		})
	);
};

export default formatCurrency;
